### ISSUE TITLE
Game crashes upon startup

### ISSUE THREAD

**Issue by Phweeeee** [MantisYT5818/Back-in-Classic#8]
I genuinely have no idea what mod or mods are causing this. But, here, Here's the latest and debug logs. (I'm using Back in Classic 0.5.3 release)

P.S, Do you have a discord? This would be a bit easier to do  that way.
[latest.log](https://github.com/MantisYT5818/Back-in-Classic/files/7214243/latest.log)
[debug.log](https://github.com/MantisYT5818/Back-in-Classic/files/7214245/debug.log)

**Comment by MantisYT5818** [comment]
I do have discord, I didn't get the notification. Sorry!

**Comment by Phweeeee** [comment]
Sorry for being absolutely absent.

**Comment by Phweeeee** [comment]
I'll give you my discord so you can add yourself. 

Phwee🧣#7974

Or you can find me as a moderator in CA.

(p.s, it works in 0.5.5)

**Comment by MantisYT5818** [comment]
Ok good, I will mark this as fixed then. Sorry about the delay!
